#!/usr/bin/env bash
EXEC=ca.ubc.cs.beta.smac.executors.ValidatorExecutor
exec java -cp "smac.jar:commons-math-2.2.jar:Jama-1.0.2.jar:commons-math3-3.0.jar:conf/:numerics4j-1.3.jar:slf4j-api-1.6.4.jar:commons-collections-3.2.1.jar:commons-io-2.1.jar:fastrf.jar:jcommander.jar:rundispatcher.jar:opencsv-2.3.jar:aclib.jar:sm.jar:truezip-samples-7.4.3-jar-with-dependencies.jar:logback-access-1.0.0.jar:logback-core-1.0.0.jar:logback-classic-1.0.0.jar" $EXEC "$@"
